services:

  database:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: archtabu
    ports:
      - "5000:5000"
    volumes:
      - ./database:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: "./backend/.env"
    ports:
      - "4000:4000"
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /app/backend
        - action: rebuild
          path: ./backend/package.json
    depends_on:
      - database

  frontend:
    build: ./frontend
    env_file: "./frontend/.env"
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app/frontend
        - action: rebuild
          path: ./frontend/package.json
    depends_on:
      - backend
