services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend/package.json
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app/frontend
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
      depends on:
        - frontend

