TRUNCATE TABLE experience CASCADE;
TRUNCATE TABLE experience RESTART IDENTITY;

TRUNCATE TABLE names CASCADE;
TRUNCATE TABLE names RESTART IDENTITY;

TRUNCATE TABLE people CASCADE;
TRUNCATE TABLE people RESTART IDENTITY;

TRUNCATE TABLE salaries CASCADE;
TRUNCATE TABLE salaries RESTART IDENTITY;
