TRUNCATE TABLE experience RESTART IDENTITY CASCADE;

TRUNCATE TABLE names RESTART IDENTITY CASCADE;

TRUNCATE TABLE people RESTART IDENTITY CASCADE;

TRUNCATE TABLE salaries RESTART IDENTITY CASCADE;
